name: Save Docker Image
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save
        run: |
          docker pull ghcr.io/open-webui/open-webui:0.11.0
          docker save ghcr.io/open-webui/open-webui:0.11.0 -o open-webui.tar
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: open-webui-tar
          path: open-webui.tar